version: '3'

services:
  web:
    build: Project1/Project1
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: "sqlite:latest"
