# Generated by Django 4.2.5 on 2023-10-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0002_image_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
